---
openapi: 3.0.0
info:
  title: API Chazki
  description: |
    In order to place orders for Chazki's services, endpoints were enabled to record the delivery and check the orders status. These services are registered in the domain owned by chazki and are detailed in the section below.
    Find out more about [Chazki here](https://chazki.com/#/).
    See also our
  termsOfService: https://chazki.com/tyc.html
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
  - url: https://us-central1-chazki-link-dev.cloudfunctions.net
    description: Tonny Development
  - url: https://us-central1-chazki-link-beta.cloudfunctions.net
    description: Tonny Beta
  - url: https://us-central1-chazki-link.cloudfunctions.net
    description: Tonny Production
tags:
  - name: WebServices
    description: List of endpoints for register and consult of the orders status.
  - name: PDFServices
    description: PDF creator endpoints.
  - name: CSVEndpoints
    description: List of endpoints for CSV file processing methods
  - name: PDFAtariServices
    description: PDF creator endpoints.
paths:

components:
