---
openapi: 3.0.0
info:
  title: Perú Legacy API
  description: |
    This documentation is only valid for Peru. In order to place orders 
    for Chazki services, endpoints were set up to record delivery and check 
    the status of orders.
    These services are registered in the domain owned by chazki and are 
    detailed in the section below.
    Find more about [Chazki here](https://chazki.com/#/). 
    See also our [Terms and Conditions](https://pe.chazki.com/tyc.html).
    ## Autenticación
    To get access to our API we use a key "chazki-api-key" that must be 
    included in the header of each request to the server.
  termsOfService: https://chazki.com/tyc.html
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
  - url: https://us-central1-chazki-link-dev.cloudfunctions.net/cf-custom-integrations-dev/api/legacy/peru
    description: Legacy Development
  - url: https://us-central1-chazki-link-beta.cloudfunctions.net/cf-custom-integrations-dev/api/legacy/peru
    description: Legacy Beta
  - url: https://us-central1-chazki-link.cloudfunctions.net/cf-custom-integrations-dev/api/legacy/peru
    description: Legacy Production
tags:
  - name: WebServices
    description: List of endpoints for register and consult of the orders status.
  - name: Anexos
    description: List of tables info.
paths:
  "/create/delivery-service":
    post:
      tags:
        - WebServices
      description:
        This endpoint allows you to register a delivery or route. 
        Since the shipment is an arrangement, several points can be 
        registered where you want the Chazki to arrive, therefore, a 
        route is formed; otherwise, only one arrival point can be registered.
      operationId: delivery-service
      parameters:
        - name: code
          in: query
          description: Delivery track code.
          required: true
          style: form
          explode: false
          schema:
            type: string
        - name: enterpriseKey
          in: query
          description: Client unique authorization code.
          required: true
          style: form
          explode: false
          schema:
            type: string
      responses:
        "200":
          description: Successfully response object.
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    type: number
                    example: 1
                  position:
                    type: object
                    properties:
                      latitude:
                        type: number
                        example: -12.046502
                      longitude:
                        type: number
                        example: -77.042716
                  status:
                    type: number
                    example: ASSIGNED
                  timestamp:
                    type: string
                    example: "2020-04-30T00:00:00.000Z"
                  rd:
                    type: string
                    example: Nombre repartidor
        "400":
          description: Query response with errors.
          content:
            application/json:
              schema:
                type: object
                "$ref": "#/components/schemas/FailFnResponse"
  "/tracking/select/delivery-code":
    get:
      tags:
        - WebServices
      description:
        This API allows us to see the movement of the Chazki and the status of the delivery.
      operationId: Status-position of the order
      parameters:
        - "$ref": '#/components/parameters/chazkiApiKey'
        - "$ref": '#/components/parameters/queryCode'
        - "$ref": '#/components/parameters/queryTimeZone'
        - "$ref": '#/components/parameters/queryLanguage'
      responses:
        "200": 
          description: Successfully response object.
          content:
            application/json:
              schema:
                type: object
                properties:
                  position:
                    type: object
                    description: Latitude and longitude points.
                    properties:
                      latitude:
                        type: number
                        example: 0
                      longitude:
                        type: number
                        example: 0
                  status:
                    type: number
                    description: State in which the delivery.
                    example: ASSIGNED
                  timestamp:
                    type: string
                    description: Date of the last update of the Chazki position.
                    example: "2020-04-30T00:00:00.000Z"
                  rd:
                    type: string
                    description: Name of the Chazki.
                    example: Drive name 
                  cel:
                    type: string
                    description: Chazki's phone.
                    example: Number Phone 
                  motivo: 
                    type: string
                    description: The reason is displayed if any failure occurred.
                    example: Client not available
        "400":
          description: Query response with errors.
          content:
            application/json:
              schema:
                type: object
                "$ref": "#/components/schemas/FailFnResponse"
  "/status/record":
    get:
      tags:
        - WebServices
      description: |
        This API allows us to see the states through which the delivery passed grouped 
        by services. The grouping of services refers to the attempts that were made to 
        deliver the delivery.
      operationId: History state
      parameters:
        - "$ref": '#/components/parameters/chazkiApiKey'
        - "$ref": '#/components/parameters/queryCode'
        - "$ref": '#/components/parameters/queryTimeZone'
      responses:
        "200": 
          description: Successfully response object.
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    type: number
                    example: 1
                  descriptionResponse: 
                    type: string
                    description: Response description
                    example: SUCCESS
                  message: 
                    type: string
                    description: message description
                    example: ""
                  "service_1":
                    type: array
                    description: Services through which the delivery passed
                    items:
                        type: object
                        "$ref": "#/components/schemas/service"
                  "service_2":
                    type: array
                    description: Services through which the delivery passed
                    items:
                        type: object
                        "$ref": "#/components/schemas/service"
        "400":
          description: Query response with errors.
          content:
            application/json:
              schema:
                type: object
                "$ref": "#/components/schemas/FailFnResponse"
  "/status/record/all":
    get:
      tags:
        - WebServices
      description: |
        This API allows us to see the states through which the delivery passed grouped 
        by services. The grouping of services refers to the attempts that were made to 
        deliver the delivery.
      operationId: History internal states
      parameters:
        - "$ref": '#/components/parameters/chazkiApiKey'
        - "$ref": '#/components/parameters/queryCode'
        - "$ref": '#/components/parameters/queryTimeZone'
      responses:
        "200": 
          description: Successfully response object.
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    type: number
                    example: 1
                  descriptionResponse: 
                    type: string
                    description: Response description
                    example: SUCCESS
                  timezone: 
                    type: string
                    description: Indicates the timezone used, by default "UTC"
                    example: "UTC"
                  statusList:
                    type: array
                    description: Array with all states of the order (internal states of chazki)
                    items:
                        type: object
                        "$ref": "#/components/schemas/serviceAll"
        "400":
          description: Query response with errors.
          content:
            application/json:
              schema:
                type: object
                "$ref": "#/components/schemas/FailFnResponse"
  "/tracking/images":
    get:
      tags:
        - WebServices
      description:
        This API allows us to see the photos taken by the chazki at the time of delivery.
      operationId: Images of the Order
      parameters:
        - "$ref": '#/components/parameters/chazkiApiKey'
        - "$ref": '#/components/parameters/queryCode'
        - "$ref": '#/components/parameters/queryLanguage'
      responses:
        "200": 
          description: Successfully response object.
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    type: number
                    description: 'Code response (0: Error, 1: Ok).'
                    example: 1
                  deliveryResponse: 
                    type: string
                    description: Code description.
                    example: SUCCESS
                  status: 
                    type: string
                    description: Status of the order at the time of the request.
                    example: "UTC"
                  orderAssociated:
                    type: string
                    description: Base64 image of the chazki associated with the order.
                    example: iVBORw0KGgoAAAANSUhEUgAAAl8AAAQ4CAIAAAC4
                  orderImages:
                    type: array
                    description: Base64 images taken by the chazki associated with the order.
                    items:
                      type: string
                      example: iVBORw0KGgoAAAANSUhEUgAAAl8AAAQ4CAIAAAC4
        "400":
          description: Query response with errors.
          content:
            application/json:
              schema:
                type: object
                "$ref": "#/components/schemas/FailFnResponse"
  "/tracking/label":
    get:
      tags:
        - WebServices
      description:
        This API allows us to obtain a label with the address of the order.
      operationId: Single Labels
      parameters:
        - "$ref": '#/components/parameters/chazkiApiKey'
        - "$ref": '#/components/parameters/queryCode'
      responses:
        "200": 
          description: Successfully response object.
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    type: number
                    description: 'Code response (0: Error, 1: Ok).'
                    example: 1
                  deliveryResponse: 
                    type: string
                    description: PDF of the order label in base 64
                    example: iVBORw0KGgoAAAANSUhEUgAAAl8AAAQ4CAIAAAC4
        "400":
          description: Query response with errors.
          content:
            application/json:
              schema:
                type: object
                "$ref": "#/components/schemas/FailFnResponse"
  "/tracking/label/all":
    post:
      tags:
        - WebServices
      description:
        This API allows us to obtain a label with the address of the order.
      security:
        - chazki-api-key: []
      operationId: Group Labels
      parameters:
        - "$ref": '#/components/parameters/chazkiApiKey'
      requestBody:
        content:
          application/json:
            schema:
              - name: trackCodes
                in: body
                description: List of registered trackCodes.
                required: true
                style: form
                explode: false
                schema:
                  type: array
                  items:
                    type: string
                    example: NroOrden1
      responses:
        "200": 
          description: Successfully response object.
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    type: number
                    description: 'Code response (0: Error, 1: Ok).'
                    example: 1
                  deliveryResponse: 
                    type: string
                    description: PDF of the order label in base 64
                    example: iVBORw0KGgoAAAANSUhEUgAAAl8AAAQ4CAIAAAC4
        "400":
          description: Query response with errors.
          content:
            application/json:
              schema:
                type: object
                "$ref": "#/components/schemas/FailFnResponse"
components:
  schemas:
    FailFnResponse:
      type: object
      properties:
        response:
          type: number
          description: 'Code response (0: Error, 1: Ok).'
          example: 0
        descriptionResponse:
          type: string
          description: Bug Description.
          example: El trackcode no existe o el enterpriseKey no es correcto
    service:
      type: object
      properties:
        status:
          type: string
          description: Delivery status
          example: NEW
        date:
          type: string
          description: Status date
          example: "2020-04-30T00:00:00.000Z"
        reason:
          type: string
          description: |
            Only for failed states. Reason if the status was "Pickup Failed" 
            or "Delivery Failed"
          example: ""
        reasonCode:
          type: string
          description: |
            Only for failed states. Reason code if the status was "Pickup Failed" 
            or "Delivery Failed"
          example: ""
    serviceAll:
      type: object
      properties:
        status:
          type: string
          description: Delivery status
          example: NEW
        date:
          type: string
          description: Status date
          example: "2020-04-30T00:00:00.000Z"
        attemptNumber:
          type: number
          description: |
            Indicates the number of delivery attempts, it increases based on rescheduling. 
            By default 1
          example: 1
        reason:
          type: string
          description: |
            Only for failed states. Reason if the status was "Pickup Failed" 
            or "Delivery Failed"
          example: ""
        reasonCode:
          type: string
          description: |
            Only for failed states. Reason code if the status was "Pickup Failed" 
            or "Delivery Failed"
          example: ""
  parameters:
    chazkiApiKey:
      name: "chazki-api-key"
      in: header
      description: Access key for api.
      required: true
      style: form
      explode: false
      schema:
        type: apiKey
    queryCode:
      name: code
      in: query
      description: Delivery track code.
      required: true
      style: form
      explode: false
      schema:
        type: string
    queryTimeZone:
      name: timezone
      in: query
      description: Timezone of city. [Anexo Timezone](https://chazki.com/#/)
      required: false
      style: form
      explode: false
      schema:
        type: string
    queryLanguage:
      name: language
      in: query
      description: Language for message response.
      required: false
      style: form
      explode: false
      schema:
        type: string
  securitySchemes:
    chazki-api-key:
      name: chazki-api-key
      type: apiKey
      in: header
      description: SigniFlow API Key
      example: xxXXxxXX-xXx-xXxX-XxXx-xxXXxxXXxxXX