---
openapi: 3.0.0
servers:
  - url: https://us-central1-chazki-link-dev.cloudfunctions.net/nintendo-cf-integrations/api
    description: Development server
  - url: https://us-central1-chazki-link-beta.cloudfunctions.net/nintendo-cf-integrations/api
    description: Beta server
  - url: https://us-central1-chazki-link.cloudfunctions.net/nintendo-cf-integrations/api
    description: Production server
info:
  version: 1.0.0
  description: |
    # Introduction
    Placeholder
    

  # version: 1.0.0
  title: Shopify API

tags:
  - name: Register
    description: List of endpoints to register a shop
  - name: OrderServices
    description: List of endpoints to manage orders

paths:
  /shopify/url-register:
    get:
      tags:
        - Register
      description: This endpoint redirects the user to a site in order to finish the integration
      operationId: url-register
      responses:
        200:
          description: Successfull operation
  /shopify/code-client:
    post:
      tags:
        - Register
      description: 
        This endpoint completes the integration. Obtains data 
        needed to allow the communication between the API's.
        Register new endpoints that will be used by the shop when an order
        is generated.
      operationId: code-client
      responses:
        200:
          description: Successfull response
        400:
          description: Unsuccessfull response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success: 
                    type: boolean
                    example: false
                  message: 
                    type: string
                    example: "ERROR_MSG"
