---
openapi: 3.0.0
servers:
  - url: https://us-central1-chazki-link-dev.cloudfunctions.net/nintendo-cf-integrations/api
    description: Development server
  - url: https://us-central1-chazki-link-beta.cloudfunctions.net/nintendo-cf-integrations/api
    description: Beta server
  - url: https://us-central1-chazki-link.cloudfunctions.net/nintendo-cf-integrations/api
    description: Production server
info:
  version: 1.0.0
  description: |
    # Introduction
    Placeholder
    

  # version: 1.0.0
  title: Shopify API

tags:
  - name: RegisterServices
    description: List of endpoints to register a shop
  - name: OrderServices
    description: List of endpoints to manage orders

paths:
  /shopify/url-register:
    get:
      tags:
        - RegisterServices
      description: This endpoint redirects the user to a site in order to finish the integration
      operationId: url-register
      parameters:
        - "$ref": '#/components/parameters/queryshop'
      responses:
        200:
          "$ref": '#/components/responses/urlregister200'
  /shopify/code-client:
    post:
      tags:
        - RegisterServices
      description: 
        This endpoint completes the integration. Obtains data 
        needed to allow the communication between the API's.
        Register new endpoints that will be used by the shop when an order
        is generated.
      operationId: code-client
      requestBody:
        "$ref": '#/components/requestBodies/code-client'
      responses:
        200:
          "$ref": '#/components/responses/codeclient200'
        400:
          "$ref": '#/components/responses/codeclient400'
  /shopify/register-webhook:
    post: 
      tags:
        - RegisterServices
      description:
        This endpoint allows a shop to recieve webhooks and register an endpoint in which the 
        webhook will be sent
      operationId: register-webhook
      requestBody:
        required: true
        content:
          application/json:
            schema:
              "$ref": '#/components/schemas/DtoShopifyRegisterWebhookShopifyRequest'
      responses:
        200: 
          "$ref": '#/components/responses/registerwebhook200'
        400:
          "$ref": '#/components/responses/registerwebhook400'
        500:
          "$ref": '#/components/responses/registerwebhook500'
  /shopify/register-shipping-cost:
    post:
      tags:
        - RegisterServices
      description: 
        This endpoint register an endpoint in which 
        a 'shipping cost' query will be sent
      operationId: register-shipping-cost
      responses:
        200:
          description: Successfull operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "SUCCESS."
                  response:
                    type: object
                    example: 'object'
        400:
          description: Unsuccessfull operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: 'ERROR_MSG'
  /shopify/shipping-cost:
    post:
      tags:
        - OrderServices
      description: 
        This endpoint let the user obtain the shipping cost of a specific order
      operationId: shiping-cost
      responses:
        200:
          description: Successfull operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    type: object
                    example: 'object'
        400:
          description: Unsuccessfull operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: 'ERROR_MSG'   
  /shopify/send-webhook-shopify:
    post:
      tags:
        - OrderServices
      description: 
        This endpoint send a webhook to the shopify API.
      operationId: send-webhook-shopify
      responses:
        200:
          description: Successfull operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "SEND WEBHOOK CORRECTLY."
        400:
          description: Unsuccessfull operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: 'ERROR_MSG'

components:
  schemas:
    ShopifyTokenRequest:
      type: object
      properties:
        code:
          type: string
          description: Code used to generate a shopify token for the first time.
          example: "XXXXXXXXXXXXXXXXXXXXXXX"
        hmac:
          type: string
          description: Security code that identifies an authentic shopify client.
          example: "XXXXXXXXXXXXXXXXXXXXXXXX"
        host:
          type: string
          description: Security code that is stored.
          example: "XXXXXXXXXXXXXXXXXXXXXXXX"
        state:
          type: string
          description: Security method that identifies a client from chazki to shopify.
          example: "s%3Apruebasintegracionmyshopifycomcreandochazki1015"
        shop:
          type: string
          description: Url that identifies a shop
          example: "https://pruebasintegracion.myshopify.com/"
        access_token:
          type: string
          description: Key that allows query responses
          example: "XXXXX_XXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
        enterpriseKey:
          type: string
          description: 
            Company identifier, it is a hash generated by Chazki to identify the company, 
            it is obtained once the company has been generated within Chazki by the commercial area.
          example: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
    DtoShopifyRegisterWebhookShopifyRequest:
      type: object
      properties:
        shop:
          type: string
          description: Url that identifies a shop
          example: "https://pruebasintegracion.myshopify.com/"
        access_token:
          type: string
          description: Key that allows query responses
          example: "XXXXX_XXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
  requestBodies:
    code-client:
      content:
        application/json:
          schema:
            properties:
              code:
                type: string
                description: Code used to generate a shopify token for the first time.
                example: "XXXXXXXXXXXXXXXXXXXXXXX"
              hmac:
                type: string
                description: Security code that identifies an authentic shopify client.
                example: "XXXXXXXXXXXXXXXXXXXXXXXX"
              host:
                type: string
                description: Security code that is stored.
                example: "XXXXXXXXXXXXXXXXXXXXXXXX"
              state:
                type: string
                description: Security method that identifies a client from chazki to shopify.
                example: "s%3Apruebasintegracionmyshopifycomcreandochazki1015"
              shop:
                type: string
                description: Url that identifies a shop
                example: "https://pruebasintegracion.myshopify.com/"
      required: true
  responses:
    urlregister200:
      description: Successfull operation
    codeclient200:
      description: Succesfull response
    codeclient400:
      description: Unsuccessfull response
      content:
        application/json:
          schema:
            type: object
            properties:
              success: 
                type: boolean
                example: false
              message: 
                type: string
                example: "ERROR_MSG"
    registerwebhook200:
      description: Successfull regsitration
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
                example: true
              message: 
                type: string
                example: "REGISTERED WEBHOOK CORRECTLY."
              response: 
                type: object
                example: ''
    registerwebhook400:
      description: Unsuccessfull registration
      content:
        application/json:
          schema:
            type: object
            properties:
              success: 
                type: boolean
                example: true
              message:
                type: string
                example: 'ERRORS REGISTERING WEBHOOK.'
              response:
                type: object
                example: ''
    registerwebhook500:
      description: Unsuccessfull registration
      content:
        application/json:
          schema:
            type: object
            properties:
              success: 
                type: boolean
                example: true
              message:
                type: string
                example: 'INTERNAL SERVER ERROR'
  parameters:
    queryshop: 
      name: shop
      in: query
      description: Url that identifies a shop
      required: true
      style: form
      explode: false
      schema:
        type: string