---
openapi: 3.0.0
servers:
  - url: https://us-central1-chazki-link-dev.cloudfunctions.net/nintendo-cf-integrations/api
    description: Development server
  - url: https://us-central1-chazki-link-beta.cloudfunctions.net/nintendo-cf-integrations/api
    description: Beta server
  - url: https://us-central1-chazki-link.cloudfunctions.net/nintendo-cf-integrations/api
    description: Production server
info:
  version: 1.0.0
  description: |
    # Introduction
    Placeholder
    

  # version: 1.0.0
  title: Shopify API

tags:
  - name: RegisterServices
    description: List of endpoints to register a shop
  - name: OrderServices
    description: List of endpoints to manage orders

paths:
  /shopify/url-register:
    get:
      tags:
        - RegisterServices
      description: This endpoint redirects the user to a site in order to finish the integration
      operationId: url-register
      parameters:
        - "$ref": '#/components/parameters/queryshop'
      responses:
        200:
          "$ref": '#/components/responses/urlregister200'
  /shopify/code-client:
    post:
      tags:
        - RegisterServices
      description: 
        This endpoint completes the integration. Obtains data 
        needed to allow the communication between the API's.
        Register new endpoints that will be used by the shop when an order
        is generated.
      operationId: code-client
      requestBody:
        "$ref": '#/components/requestBodies/code-client'
      responses:
        200:
          "$ref": '#/components/responses/codeclient200'
        400:
          "$ref": '#/components/responses/codeclient400'
  /shopify/register-webhook:
    post: 
      tags:
        - RegisterServices
      description:
        This endpoint allows a shop to recieve webhooks and register an endpoint in which the 
        webhook will be sent
      operationId: register-webhook
      requestBody:
        required: true
        content:
          application/json:
            schema:
              "$ref": '#/components/schemas/DtoShopifyRegisterWebhookShopifyRequest'
      responses:
        200: 
          "$ref": '#/components/responses/registerwebhook200'
        400:
          "$ref": '#/components/responses/registerwebhook400'
        500:
          "$ref": '#/components/responses/registerwebhook500'
  /shopify/register-shipping-cost:
    post:
      tags:
        - RegisterServices
      description: 
        This endpoint register an endpoint in which 
        a 'shipping cost' query will be sent
      operationId: register-shipping-cost
      requestBody:
        required: true
        content:
          application/json:
            schema:
              "$ref": '#/components/schemas/DtoShopifyRegisterShippingCostRequest'
      responses:
        200:
          "$ref": '#/components/responses/registershipcost200'
        400:
          "$ref": '#/components/responses/registershipcost400'
        500:
          "$ref": '#/components/responses/registershipcost500'
  /shopify/shipping-cost:
    post:
      tags:
        - OrderServices
      description: 
        This endpoint let the user obtain the shipping cost of a specific order
      operationId: shiping-cost
      parameters:
        - in: header
          name: 'x-shopify-shop-domain'
          schema:
            type: string
          example: 'https://pruebasintegracion.myshopify.com/'
      requestBody: 
        required: true
        content:
          application/json:
            schema:
              "$ref": '#/components/schemas/DtoShopifyShippingCostBody'
      responses:
        200:
          "$ref": '#/components/responses/shippingcost200'
        400:
          "$ref": '#/components/responses/shippingcost400'
  /shopify/send-webhook-shopify:
    post:
      tags:
        - OrderServices
      description: 
        This endpoint send a webhook to the shopify API.
      operationId: send-webhook-shopify
      responses:
        200:
          description: Successfull operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "SEND WEBHOOK CORRECTLY."
        400:
          description: Unsuccessfull operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: 'ERROR_MSG'

components:
  schemas:
    DtoShopifyTokenRequest:
      type: object
      properties:
        code:
          type: string
          description: Code used to generate a shopify token for the first time.
          example: "XXXXXXXXXXXXXXXXXXXXXXX"
        hmac:
          type: string
          description: Security code that identifies an authentic shopify client.
          example: "XXXXXXXXXXXXXXXXXXXXXXXX"
        host:
          type: string
          description: Security code that is stored.
          example: "XXXXXXXXXXXXXXXXXXXXXXXX"
        state:
          type: string
          description: Security method that identifies a client from chazki to shopify.
          example: "s%3Apruebasintegracionmyshopifycomcreandochazki1015"
        shop:
          type: string
          description: Url that identifies a shop
          example: "https://pruebasintegracion.myshopify.com/"
        access_token:
          type: string
          description: Key that allows query responses
          example: "XXXXX_XXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
        enterpriseKey:
          type: string
          description: 
            Company identifier, it is a hash generated by Chazki to identify the company, 
            it is obtained once the company has been generated within Chazki by the commercial area.
          example: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
      required:
        - code
        - hmac
        - host
        - state
        - shop
    DtoShopifyRegisterWebhookShopifyRequest:
      type: object
      properties:
        shop:
          type: string
          description: Url that identifies a shop
          example: "https://pruebasintegracion.myshopify.com/"
        access_token:
          type: string
          description: Key that allows query responses
          example: "XXXXX_XXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
      required:
        - shop
        - access_token
    DtoShopifyRegisterShippingCostRequest:
      type: object
      properties:
        shop:
          type: string
          description: Url that identifies a shop
          example: "https://pruebasintegracion.myshopify.com/"
        access_token:
          type: string
          description: Key that allows query responses
          example: "XXXXX_XXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
      required:
        - shop
        - access_token
    DtoShopifyShippingCostResponse:
      type: object
      properties:
        shippingcost:
          type: object
          "$ref": '#/components/schemas/DtoRateShippingCost'
    DtoRateShippingCost:
      type: array
      items:
        "$ref": '#/components/schemas/DtoShippingCostResponse'
    DtoShippingCostResponse:
      type: object
      properties:
        service_name:
          type: string
          description: Name of the service
          example: ''
        description: 
          description: ''
          type: string
          example: ''
        service_code: 
          type: string
        currency: 
          description: Currency used in the service
          type: string
          example: ''
        total_price: 
          description: Price of the service
          type: number
          example: ''
        phone_required:
          description: ''
          type: string
          example: ''
        min_delivery_date:
          description: ''
          type: string
          example: ''
        max_delivery_date: 
          description: ''
          type: string
          example: ''
      required:
        - service_name
        - description
        - service_code
        - currency
        - total_price
        - phone_required
        - min_delivery_date
        - max_delivery_date

    DtoLocationRate:
      type: object
      properties:
        country: 
          description: Country abbreviation for delivery
          type: string
          example: 'CL'
        postal_code: 
          description: Code to identify a zone 
          type: string
          example: 'XXXXXXX'
        province: 
          description: Province abbreviation for delivery
          type: string
          example: 'RM'
        city: 
          description: City for delivery
          type: string
          example: 'La Florida'
        name: 
          description: Person's contact name 
          type: string
          example: 'Juan Perez'
        address1: 
          type: string
          example: ''
        address2: 
          type: string
          example: ''
        address3: 
          type: string
          example: ''
        phone: 
          description: Person's contact number
          type: string
          example: 123456789
        fax: 
          type: string
          example: 
        email: 
          description: Person's email address
          type: string
          example: 'xxxxxxx@yyyyy.zzz'
        address_type: 
          type: string
          example: 
        company_name: 
          type: string
          example: 'XXXXXXXXXXXXX'
      required:
        - country
        - postal_code
        - province
        - city
        - name
        - address1
        - address2
        - address3
        - phone
        - fax
        - email
        - address_type
        - company_name      
    DtoItems:
      type: object
      properties:
        id: 
          description: Item identifier
          type: number
          example: 12345
        admin_graphql_api_id: 
          type: string
          example: ''
        destination_location: 
          type: string
          example: ''
        fulfillable_quantity: 
          type: number
          example: ''
        fulfillment_service: 
          type: string
          example: ''
        fulfillment_status: 
          type: string
          example: ''
        gift_card: 
          type: boolean
          example: ''
        grams: 
          description: Grams per item
          type: number
          example: '800'
        name: 
          description: Name of the item
          type: string
          example: 'XXXXXXXXXX'
        origin_location: 
          type: string
          example: ''
        price: 
          description: Price per item
          type: number
          example: '400'
        price_set: 
          type: string
          example: ''
        product_exists: 
          type: boolean
          example: ''
        product_id: 
          description: Number that identifies a product
          type: number
          example: 'xxxxxxxxxx'
        properties: 
          type: string
          example: ''
        quantity: 
          type: number
          example: ''
        requires_shipping: 
          description: Wether the item needs to me shipped or not
          type: boolean
          example: 'true'
        sku: 
          type: string
          example: ''
        taxable: 
          description: Wether the item is taxable or not
          type: boolean
          example: 'true'
        title: 
          type: string
          example: ''
        total_discount: 
          type: number
          example: ''
        total_discount_set: 
          type: string
          example: ''
        variant_id: 
          type: number
          example: 'xxxxxxxxxx'
        variant_inventory_management: 
          type: string
          example: ''
        variant_title: 
          type: string
          example: ''
        vendor: 
          type: string
          example: 'XXXXXXXXXX'
        tax_lines: 
          type: string
          example: ''
        duties: 
          type: string
          example: ''
        discount_allocations: 
          type: string
          example: ''
      required:
        - id
        - name
        - quantity
        - grams
        - price
        - product_id
        - variant_id
        - vendor
    DtoRateShipping:
      type: object
      properties:
        origin:
          "$ref": '#/components/schemas/DtoLocationRate'
        destination:
          "$ref": '#/components/schemas/DtoLocationRate'
        items:
          type: array
          items:
            "$ref": '#/components/schemas/DtoItems'
        currency:
          description: Abbreviation of the currency used in the payment.
          type: string
          example: 'PEN'
        locale:
          type: string
          example: ''
      required:
        - currency
        - locale
    DtoShopifyShippingCostBody:
      type: object
      properties:
        rate:
          type: object
          "$ref": '#/components/schemas/DtoRateShipping'
        currency:
          description: Abbreviation oof the currency used in the payment
          type: string
          example: 'PEN'
        locale:
          type: string
          example: ''
      required:
        - currency
        - locale
  requestBodies:
    code-client:
      content:
        application/json:
          schema:
            properties:
              code:
                type: string
                description: Code used to generate a shopify token for the first time.
                example: "XXXXXXXXXXXXXXXXXXXXXXX"
              hmac:
                type: string
                description: Security code that identifies an authentic shopify client.
                example: "XXXXXXXXXXXXXXXXXXXXXXXX"
              host:
                type: string
                description: Security code that is stored.
                example: "XXXXXXXXXXXXXXXXXXXXXXXX"
              state:
                type: string
                description: Security method that identifies a client from chazki to shopify.
                example: "s%3Apruebasintegracionmyshopifycomcreandochazki1015"
              shop:
                type: string
                description: Url that identifies a shop
                example: "https://pruebasintegracion.myshopify.com/"
      required: true
  responses:
    urlregister200:
      description: Successfull operation
    codeclient200:
      description: Succesfull response
    codeclient400:
      description: Unsuccessfull response
      content:
        application/json:
          schema:
            type: object
            properties:
              success: 
                type: boolean
                example: false
              message: 
                type: string
                example: "ERROR_MSG"
    registerwebhook200:
      description: Successfull registration
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
                example: true
              message: 
                type: string
                example: "REGISTERED WEBHOOK CORRECTLY."
              response: 
                type: object
                example: ''
    registerwebhook400:
      description: Unsuccessfull registration
      content:
        application/json:
          schema:
            type: object
            properties:
              success: 
                type: boolean
                example: true
              message:
                type: string
                example: 'ERRORS REGISTERING WEBHOOK.'
              response:
                type: object
                example: ''
    registerwebhook500:
      description: Unsuccessfull operation
      content:
        application/json:
          schema:
            type: object
            properties:
              success: 
                type: boolean
                example: true
              message:
                type: string
                example: 'INTERNAL SERVER ERROR'
    registershipcost200:
      description: Successfull registration
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
                example: true
              message: 
                type: string
                example: "SUCCESS"
              response: 
                type: object
                example: ''
    registershipcost400:
      description: Unsuccessfull registration
      content:
        application/json:
          schema:
            type: object
            properties:
              success: 
                type: boolean
                example: true
              response:
                type: object
                example: ''
    registershipcost500:
      description: Unsuccessfull operation
      content:
        application/json:
          schema:
            type: object
            properties:
              success: 
                type: boolean
                example: true
              message:
                type: string
                example: 'INTERNAL SERVER ERROR'
    shippingcost200:
      description: Successfull operation
      content:
        application/json:
          schema:
            "$ref": '#/components/schemas/DtoShippingCostResponse'
    shippingcost400:
      description: Unsuccessfull operation
      content:
        application/json:
          schema:
            type: object
            properties:
              success: 
                type: boolean
                example: false
              message:
                type: string
                example: ''
            
  parameters:
    queryshop: 
      name: shop
      in: query
      description: Url that identifies a shop
      required: true
      style: form
      explode: false
      schema:
        type: string